<?php


/**
 * PLEASE DO NOT EDIT THIS FILE.
 * 
 * (Unless you are contributing to improving it, 
 * via Open Source collaboration)
 * 
 * The reason is, if you are the end-user, this file can be 
 * regularly upgraded as part of a published improvement or bug
 * fix to Code_Alchemy Composer and Application Director
 * 
 * If you absolutely feel you need to make a change, contact
 * us instead and make a new feature request, or, if you are a 
 * software developer, feel free to make a contribution.
 * 
 * Contact us for any reason at info@alquemedia.com
 * 
 * This file is part of Code_Alchemy Framework for PHP and jQuery
 * 
 * This application uses PHP, MySQL, JavaScript, jQuery, Handlebars, LESS, 
 *  and Twitter Bootstrap 3.
 *
 * Some of our code is based on licensed templates, such as "Angle", "Flati"
 * and "Toranj."  In every such case, all end-deployed websites, have a 
 * specific purchased and paid license of use, from the respective authors, 
 * and we encourage all such installations to do the same.
 * 
 * Those guys work really hard to save us downstream developers hundreds of 
 * hours of time with their incredible work.  Let's be sure to pay them
 * a small cash value, for their immense use value.
 *
 * PHP version 5.4 or greater is always recommended.
 *
 * @category  Code_Alchemy
 * @package   Composer and Application Director
 * @author    David Greenberg <david@alquemedia.com>
 * @copyright 2015 Authors
 * @license   MIT <http://opensource.org/licenses/MIT>
 * @link      http://www.alquemedia.com
 */


$webroot = \Code_Alchemy\Core\Code_Alchemy_Framework::instance()->webroot();

// Get Controller
$controller = get_controller( $this );

// Get State
$state = $controller->state();

$data = $controller->data();

$data_object = $controller->data_as_object();

$action = $controller->uri()->part(2);

$model = $controller->uri()->part(3);

$model_id = $controller->uri()->part(4);

$commmand = $controller->uri()->part(5);

$services = $data['services'];

$columns = $data['all_columns'];

$shown_columns = $data['shown_columns'];

$models = $data['models'];

$fields = $data['fields'];

$lang = (string) \Code_Alchemy\Core\Code_Alchemy_Framework::instance()->configuration()->language;

$ref = $data['reference_column'];

//$is_sortable_class = $data['is_sortable']?'is-sortable':'';
$is_sortable_class = 'is-sortable';

$per_page = $controller->uri()->part(5);

$page_number = $controller->uri()->part(4);

$last_page = $data['last_page'];

$supports_soft_delete = $data['supports_soft_delete'];

$delete_icon = $supports_soft_delete? 'fa-archive':'fa-trash';

$data = $controller->data_as_object();

$fields = $data->fields;

$select_service_title = $lang =='es'?
    'Salta rapidamente a otro listado cambiando este valor':
    'Quickly jump to another service view by changing this value';

$scope = $data;

$custom_actions = $scope->custom_actions;

$id_column = (new \Code_Alchemy\Database\Postgres\State\Is_PostgreSQL())->bool_value() ?
    
    $model."_id": 'id';

?>
<!DOCTYPE html>
<html>
<head>
    <?php
    require_once $webroot ."/app/views/components/parnassus-head.php";
    ?>
</head>
<body  onload="webDirector.disable_preloader()">

<?php
    require_once $webroot ."/app/views/components/parnassus-nav.php";
?>

    <div id="wrapper">

        <?php require_once $webroot."/app/views/components/ca-sidebar-wrapper.php";?>

    <div id="page-content-wrapper">

        <div style="" class="container content-container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="page-header">
                        <h1 class="clearfix" id="tables">

                            <select class="pull-left form-control" id="select-service" name="select_service">
                                <?php foreach ( $controller->data_as_object()->services as $service ){

                                    $selected = strtolower($controller->data_as_object()->label) == strtolower($service['service_label'])? 'selected="selected"':'';

                                    ?>
                                    <option <?=$selected?> value="<?=$service['table_name']?>"><?=$service['service_label']?></option>
                                <?php } ?>
                            </select>
                            <select class="pull-left form-control" id="page-size" style="margin-left: 20px; width: 200px;" name="page_size">
                                <?php foreach( array(5,10,25,50,100) as $page_size){
                                    $show_label = $data_object->language =='es'?"Mostrar $page_size registros": "Show $page_size records";?>

                                    ?>
                                    <option <?=$page_size==$per_page?'selected="selected"':''?> value="<?=$page_size?>"><?=$show_label?></option>
                                <?php } ?>
                            </select>

                            <a href="/parnassus/add/<?=$data['model_class']?>" class="btn btn-primary">
                                <i class="fa fa-plus-circle"></i>
                                &nbsp; <?=$lang=='es'?'Agregar':'Add'?>
                            </a>

                            <a href="#" class="btn btn-warning edit-view">
                                <i class="fa fa-pencil-square-o"></i>
                                &nbsp; <span class="label">Edit View</span>
                            </a>


                        </h1>

                        <!-- alerts here -->
                        <?php if ( isset($data['new_model_id']) || isset( $data['edited_model_id']) ){?>
                            <div class="alert alert-dismissable alert-success">
                                <button data-dismiss="alert" class="close" type="button">×</button>
                                <strong>Well done!</strong> Your changes have been saved
                            </div>
                        <?php } ?>


                        <p>

                            <!-- New!  Support for multi-add -->
                            <?php if ( isset( $data['model_configuration']['multi-add'])) {?>
                                <a href="/parnassus/multi-add/<?=$data['model_class']?>" class="btn btn-primary">
                                    <i class="fa fa-plus-circle"></i>
                                    &nbsp; <?=$lang=='es'?'Agregar Varios':'Multi-Add'?>
                                </a>
                            <?php } ?>

                        </p>

                        <select style="display:none;width: 400px;" class="form-control pull-left select-columns" multiple="">
                            <?php foreach ( $columns  as $col) {
                                $selected = in_array($col, $shown_columns)?'selected="selected"':'';

                                ?>
                                <option <?=$selected?> value="<?=$col?>"><?=$col?></option>
                            <?php } ?>
                        </select>

                        <form action="/parnassus/list_of/<?=$model?>">
                            <div class="form-group col-lg-6">
                                <select name="search_column" style="width: 40%;" id="search-col" class="pull-left form-control">
                                    <?php foreach ( $shown_columns as $col){
                                        $selected = $col == $_REQUEST['search_column']?'selected="selected"':'';

                                        ?>
                                        <option <?=$selected?> value="<?=$col?>"><?=$col?></option>
                                    <?php } ?>
                                </select>
                                <input style="width:40%;" name="search_term" id="search-term" class="pull-left form-control" value="<?=$_REQUEST['search_term']?>"/>
                            </div>

                        </form>
                        <a href="/parnassus/list_of/<?=$model?>"><i class="fa fa-times fa-2x"></i></a>


                    </div>

                    <div class="bs-component">
                        <table class="<?=$is_sortable_class?> pull-left table table-striped table-hover ">
                            <thead>
                            <tr>
                                <?php foreach ( $shown_columns as $col){?>
                                    <th><?=$col?></th>
                                <?php } ?>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>

                            <!-- Give user the option to add one quickly -->
                                <tr class="add-one">

                                    <?php foreach ( $shown_columns as $col ){

                                    $field = $fields[$col];

                                    ?>
                                    <td>

                                        <?php switch ($field->type) {

                                            case 'enum': ?>

                                                <select data-required-field="<?=$field->is_required?>" class="form-control " name="<?=$field->name?>">
                                                    <?php foreach ( $field->enum_values as $value ){?>
                                                        <option value="<?=$value?>"><?=$value?></option>
                                                    <?php }?>
                                                </select>

<?php
                                                break;

                                            default: ?>
                                                <input class="add-one" name="<?= $col ?>">
                                                <?php break;
                                        }

                                        ?>
                                    </td>
                                    <?php } ?>

                                    <td>

                                        <a class="btn btm-xs btn-primary add-one"><?=$lang=='es'?"Agregar":'Add'?></a>
                                    </td>

                                </tr>

                            <?php foreach ( $models as $mod ){?>

                                <tr data-id="<?=$mod[ $id_column ]?>">
                                    <?php foreach( $shown_columns as $col ){

                                        $field = $fields[$col];

                                        $val = $mod[ $col ];

                                        // If Boolean Yes/No
                                        if ( $field->type ==='tinyint') {

                                            $yes = $lang=='es'?'Sí':'Yes';

                                            $val = $val?$yes:'No';
                                        }

                                        // For an image
                                        if ( preg_match('/image_filename_url/',$col,$hits)) {
                                            ?>
                                            <td><img src="<?=$val?>" style="max-width: 150px;"/></td>
                                            <?php
                                        }  else { ?>
                                            <td><?=$val?></td>
                                        <?php } } ?>

                                    <?=$controller->handlebars('ca-model-actions',array(

                                        'uri' => $controller->uri()->part(3),

                                        'model_id' => $mod[ $id_column ],

                                        'title' => $data_object->tooltip_titles['edit'],

                                        'is_email_template' => !! ( $model == 'email_template' ),

                                        'template_key' => $mod['template_key'],

                                        'delete_icon' => $delete_icon,

                                        'custom_actions' => $custom_actions

                                    ));?>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                        <div class="row">
                            <ul class="pager">
                                <?php if ( $page_number>1){?>
                                    <li><a href="/parnassus/list_of/<?=$model?>/<?=($page_number-1)?>/<?=$per_page?>">Previous</a></li>
                                <?php } ?>
                                <?php if ( $last_page> $page_number ){?>
                                    <li><a href="/parnassus/list_of/<?=$model?>/<?=($page_number+1)?>/<?=$per_page?>">Next</a></li>
                                <?php } ?>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
            <?php

            require_once $webroot."/app/views/components/parnassus-footer.php";
            ?>

    </div>

        </div>

    </div>


<!--</div>-->
    <?php if ( $action == 'add'){ ?>
    <script src="/js/bootstrap-clockpicker.js"></script>
    <script src="/js/bootstrap-switch.js"></script>
    <?php } ?>
<script src="/jquery-ui/jquery-ui.min.js"></script>

<script src="/js/bloodhound.min.js"></script>
<script src="/js/typeahead.js"></script>
    <script>
        $(function(){

            // Add one quickly
            $('a.add-one').on('click',function(e){

                // collate data
                var data = '';

                $('input.add-one').each(function(){

                    $(this).removeClass('input-error');

                    data += data? '&'+$(this).attr('name')+'='+$(this).val():

                        $(this).attr('name')+'='+$(this).val();

                });

                $.ajax({

                    type: 'POST',

                    url: '/rest/<?=$model?>',

                    data: data,

                    success: function( model ){

                        // If error
                        if ( typeof(model.result)!='undefined' && model.result == 'error'){

                            toastr.error(model.error,'Error',{

                                preventDuplicates: true

                            });

                            $.each(model.codeAlchemy_data.missing_fields,function(index,field){

                               $('input.add-one[name="'+ field +'"]').addClass('input-error');

                            });

                        } else {

                            window.location.reload();
                        }

                    }
                });

            });

            // Show some tips
            $('.tooltip').tooltip();

            // Select a different service
            $('select#select-service').on('change',function(e){

                window.location.href = '/parnassus/list_of/'+$(this).val()+'/1/25';

            });

            // Change page size
            $('select#page-size').on('change',function(e){

                console.log('ok');

                window.location.href = '/parnassus/list_of/<?=$model?>/<?=$page_number?>/'+$(this).val();

            });



            $('.is-sortable tbody').sortable({

                // Only drag on y Axis
                axis: 'y',

                // Restrict sorting to helper handle
                handle: '.sort-helper',


                stop: function(event,ui){

                    var order = [];

                    $('tr').each(function(){

                        var id = $(this).attr('data-id');

                        if ( typeof(id)!='undefined' ) order.push(id);

                    });

                    console.log( order.join(',') );

                    $.ajax({
                        url: '/parnassus/reorder/<?=$model?>',
                        data: 'order='+order.join(','),
                        type: 'POST',
                        success: function(json){
                            console.log(json);
                        }
                    })

                }
            });

            // Edit the view
            $('.edit-view').on('click',function(e){

                var control = $(this);

                var select = $('.select-columns');

                if ( ! select.is(':visible') ){

                    select.show();

                    control.find('.label').html('Save Changes');

                } else {

                    var columns = select.val().join(',');

                    if ( columns.length )

                        $.ajax({

                            url: '/parnassus/set_columns_for/'+'<?=$model?>',

                            type: 'POST',

                            data: 'columns='+columns,

                            success: function(json){

                                if ( json.result == 'success')

                                    window.location.reload();
                            }
                        });
                }

            });
            // Delete an Item
            $('.delete-item').on('click',function(e){

                // Delete using API
                var id = $(this).attr('data-id');
                $.ajax({
                    type: 'DELETE',
                    url: '/rest/<?=$model?>/'+ id,
                    success: function(json){

                        if ( json.codeAlchemy_data.operation_result =='success')

                        // remove item
                            $('tr[data-id="'+id+'"]').fadeOut('fast').remove();

                        else

                            toastr.error( json.error, 'Error',{

                                preventDuplicates: true

                            });

                    }
                });

            });

        });
    </script>
    <?php if ( $model == 'email_template'){?>
    <div id="test-send" class="modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
                    <h4 class="modal-title">Test Send</h4>
                </div>
                <div class="modal-body">
                    <div style="display:none;" class="alert alert-dismissible alert-danger">
                        <button data-dismiss="alert" class="close" type="button">×</button>
                        <strong>Oh snap!</strong> <span class="message"></span>
                    </div>
                    <input class="test-email" placeholder="type email address to send"/>
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default" type="button">Close</button>
                    <button class="btn btn-primary send-email" type="button">Send Email</button>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(function(){

            $('button.send-email').on('click',function(e){

                var modal = $('#test-send');

                $.ajax({
                    type: 'POST',
                    url: '/parnassus/test_email_template/',
                    data: 'template='+modal.attr('data-template-key')+'&email='+modal.find('input').val(),
                    success: function(json){

                        if (json.result == 'success')

                            modal.modal('hide');

                        else {

                            var alert = modal.find('.alert-danger');

                            var message = alert.find('.message');

                            message.html( json.error);

                            alert.show();
                        }
                    }
                });


            });
        });
    </script>
    <?php } ?>
</body>
</html>

<?php

function get_controller(  $controller ){

    return $controller;
}

?>