<?php
/**
 * LAYOUT_POST_STUB
 *
 * Note: This code is automatically generated by Code_Alchemy
 *
 * (c) 2015 Alquemedia SAS, all rights reserved.
 */

function get_controller( Dynamic_Controller $controller ){

    return $controller;

}

