<?php

namespace yala;

/**
 * LAYOUT_PRE_STUB
 *
 * Note: This code is automatically generated by Code Alchemy.
 *
 * (c) 2015 Alquemedia SAS, all rights reserved.
 */

use Code_Alchemy\Core\Code_Alchemy_Framework;
use Code_Alchemy\Controllers\Dynamic_Controller;

// Get Controller
$controller = get_controller( $this );

// Theme root
$theme_root = "/themes/lumina/";

// Web root
$webroot = Code_Alchemy_Framework::instance()->webroot();

?>
<head>
    <meta charset="utf-8">
    <title>Please Sign In</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="stylesheet" href="<?=$theme_root?>css/bootstrap.css" media="screen">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="../bower_components/html5shiv/dist/html5shiv.js"></script>
    <script src="../bower_components/respond/dest/respond.min.js"></script>
    <![endif]-->

</head>