CREATE TABLE `__database_name__`.`__table_name__`(
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sortable_id` int(11) DEFAULT NULL,
  `title` varchar(100) NOT NULL,
  `seo_name` varchar(100) DEFAULT NULL,
  `text` longtext,
  `author_id` int(11) DEFAULT NULL,
  `website_image_id` int(11) DEFAULT NULL,
  `created_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` int(11) DEFAULT NULL,
  `last_modified_date` datetime DEFAULT NULL,
  `last_modified_by` int(11) DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT '0',
  `deleted_date` datetime DEFAULT NULL,
  `deleted_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX___table_name___unique_title` (`title`),
  KEY `IDX___table_name___created_by` (`created_by`),
  KEY `IDX___table_name___last_mf_by` (`last_modified_by`),
  KEY `IDX___table_name___deleted_by` (`deleted_by`),
  KEY `IDX___table_name___author_id` (`author_id`),
  KEY `IDX___table_name___website_image_id` (`website_image_id`),
  CONSTRAINT `FK___table_name___website_image_id` FOREIGN KEY (`website_image_id`) REFERENCES `website_image` (`id`),
  CONSTRAINT `FK___table_name___author_id` FOREIGN KEY (`author_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
